### PR TITLE
force utc

### PR DESCRIPTION
**Pull request by hsmade**
As DateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"); dictates a UTC timestamp, make sure the timestamp is indeed, UTC.

### CODE REVIEW

**Comment by hsmade** [comment]
My logs were denied by loki, as the timestamp was too far into the future (my local timezone is UTC+2), after doing this change, it works.

**Comment by hpoul** [comment]
thanks.. 👍️ 

weird that i didn't stumble on that myself, as i'm +2 as well.. 🤔️

out of curiosity, are you using loki appender for a client or server app?

**Comment by hsmade** [comment]
I'm playing with it for a 'personal' app which implements a dashboard in my house, so a client.

**Comment by hpoul** [comment]
ah okay.. was just asking, because i've got stuck using it on the client side, because each client would need it's own "labels", because all logs within one label must be in chronological order.. was wondering if this either changed or if there is some workaround 😅️ but if it's just for your house, there probably aren't that many clients :-)

**Comment by hsmade** [comment]
What I would do for that it's add a client label, with a uuid as value.
Best to be generated on startup (privacy wise).

**Comment by hpoul** [comment]
> What I would do for that it's add a client label, with a uuid as value.

that's basically the exact opposite of what [loki's documentation](https://grafana.com/blog/2020/04/21/how-labels-in-loki-can-make-log-queries-faster-and-easier/#cardinality) says about label cardinality. but ymmv, i've never tried it myself for >1000 users.. 🤷‍♂️️

**Comment by hsmade** [comment]
Yeah, that makes sense. I guess collecting logs for many clients isn't a good use case. Did you consider using Sentry?

**Pull request merged**
